# 教程文章 https://zhuanlan.zhihu.com/p/433426848

name: ci部署项目 # 定义workflow的名称
on: [push]
env:
  WEBAPP_NAME: webserver # 应用名称
  SERVER_PRIVATE_KEY: ${{ secrets.SERVER_PRIVATE_KEY }} # 服务器私钥
  SERVER_HOST: ${{ secrets.SERVER_HOST }} # 服务器IP地址
  SERVER_SSH_PORT: ${{ secrets.SERVER_SSH_PORT }} # 服务器端口
  SERVER_USER_NAME: ${{ secrets.SERVER_USER_NAME }} # 服务器用户名

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 拉起github 仓库代码到github提供的虚拟机工作地点
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: v18.18.0

      # 缓存依赖
      - name: Cache nodemodules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          # 需要缓存的文件的路径
          path: ./node_modules
          # 对缓存的文件指定的唯一标识
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./package.json') }}
          # 用于没有再找目标key的缓存的backup选项
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      # 装依赖
      - name: Install
        run: npm install

      # 打包
      - name: Build
        run: npm run build

      # 上传打包资源
      - name: Deploy
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ env.SERVER_PRIVATE_KEY }} # 私钥
          REMOTE_HOST: ${{ env.SERVER_HOST }} # 主机ip
          REMOTE_PORT: ${{ env.SERVER_SSH_PORT }} # ssh端口，默认为22
          REMOTE_USER: ${{ env.SERVER_USER_NAME }} # 登录ssh的用户名
          ARGS: "-avz --delete"
          SOURCE: "dist/" # 资源路径
          TARGET: /home/${{ env.WEBAPP_NAME }} # 服务器目标路径
